### ISSUE TITLE
Run pipeline with multiple reference genomes

### ISSUE THREAD

**Issue by rbpisupati** [nf-core/methylseq#11]
Hi, 

I would like to run the pipeline on hundreds of input files independently. Can you please suggest me how I can modify this? 

Thanks in advance,
Cheers,

**Comment by MaxUlysse** [comment]
Isn't it possible to make a script that will launch this pipeline for each file?

**Comment by rbpisupati** [comment]
I tried running this pipeline for every file using a simple for loop. But it doesnt seem to work (some of the pipelines failed and output directory has only one output). I dont know if this is due to common work directory or something else. 

PS: my nextflow script has pbs execution for the processes.

**Comment by MaxUlysse** [comment]
Have you changed the `--params.outdir` also in your loop?

**Comment by ewels** [comment]
Wait, why do you want to launch the pipeline for each sample? Is there a reason that you cannot just run the pipeline once and give it hundreds of input files? This is how Nextflow is designed to work.

Phil

**Comment by rbpisupati** [comment]
No I am not changing --params.outdir in the loop. It is a common directory


Phil, yes but the script is reading only either 2 or 1 files (https://github.com/nf-core/methylseq/blob/c2023f54ae67c931bb650307e333e9984e200e4a/main.nf#L140) based on singleEnd. 

I did try running like this and didnt seem to work
`
nextflow run ~/mygit/methylseq/main.nf --reads *fastq --fasta ~/TAiR10_ARABIDOPSIS/TAIR10_wholeGenome.fasta --outdir test_meths --singleEnd
`

**Comment by ewels** [comment]
Hi @rbpisupati,

I think that maybe you're misunderstanding how the pipeline accepts input files. The `reads` channel specifies either 1 or 2 as the _pairing_ digit. See the Nextflow docs here: https://www.nextflow.io/docs/latest/channel.html#fromfilepairs

I wrote it like this so that Nextflow will automatically group paired-end FastQ files together that are from a single sample, based on the filename pattern that you specify. The alternate value of 1 is used when `--singleEnd`  is specified; this is to make the choice between single and and paired-end explicit, as we had problems with accidental filename patterns for paired-end data running in single-end mode.

See the docs about how to use this [here](https://github.com/nf-core/methylseq/blob/master/docs/usage.md#--reads) - in short, if you use a glob pattern that matches all of the input FastQ files in your entire project, Nextflow will automatically group the paired-end pairs (if specified) and run the per-sample tasks in parallel automatically.

Let me know if I'm missing something here, or if you have any suggestions for how we could improve the pipeline documentation.

Phil

**Comment by rbpisupati** [comment]
Thanks Phil, for very prompt reply! I am just starting to migrate to nextflow and your pipeline is very helpful. 

The only reason I wanted to run it separately is because it wasnt completely clear to me how to provide even a list of difference genome reference fasta. i.e., for example you want to analyse bisulfite data for 100 genomes. In other words, does nextflow take care of two inputs with multiple files?



Rahul

**Comment by ewels** [comment]
Aha, so each 100 samples with 100 reference genomes, and each needs a different reference genome? Yes, that is not possible with the current pipeline setup. Ok, then this approach makes sense :)

Note that this would be possible to do with nextflow generally, so if you are up for the challenge you could fork the pipeline and modify it to handle this. It's not super-trivial though.

What is the error that you get when you try to loop the pipeline launch? Note that I have seen people to write a nextflow pipeline that runs another nextflow pipeline (think _inception_). I'll try to dig out the example if I can find it.

Phil

**Comment by marchoeppner** [comment]
What you could also do is to use a different input Channel construct:

Channel.from(inputFile)
       .splitCsv(sep: ';', header: true)
       .set {  inputData }

So here the input would be one CSV formatted file that lists all your samples with corresponding REF genome and fastq files. If the CSV file contains something like:

```
RefGenome;sampleId;fastq1;fastq2
GRCh37;Pete;/path/to/forward_reads;/path/to/reverse_reads
```

then the input statement for the first processing module would be:

```
input:
set file(ref_genome), sampleID , fastq1, fastq2 from inputData
```

Would take a bit of fiddling, but it's doable, I reckon

**Comment by ewels** [comment]
Ok, closing this issue now. I hope this helps @rbpisupati! Let us know if we can help any further.

**Comment by rbpisupati** [comment]
Thank you @marchoeppner and @ewels! It was simply working around the logic that you have mentioned before. 
fyi for others users, the script I have modified is here. (https://github.com/rbpisupati/methylseq/blob/master/methylpyDiffGenomes.nf).

Rahul

**Comment by ewels** [comment]
Great! Thanks for letting us know 😁
