### ISSUE TITLE
Genome not found in config 

### ISSUE THREAD

**Issue by sofiahaglund** [nf-core/methylseq#150]
Hi! 

I tried running methylseq v1.4 with command:

```bash
methylseq --pbat --clip_r1 9 --clip_r2 9 --three_prime_clip_r1 9 --three_prime_clip_r2 9 --reads "../data/*_R{1,2}.fastq.gz" --genome GRCh37 --max_memory '256.GB'
```

And I got the error:

```
No reference genome index or fasta file specified false. Expression: (params.bismark_index || params.fasta)
```

The `fasta = params.genome ? params.genomes[ params.genome ].fasta ?: false : false` does not populate the fasta parameter.

Has someone experienced this before? (“methylseq” is an alias btw)

Thanks!

**Comment by phue** [comment]
Hi @sofiahaglund 

Did you already try running the pipeline from `dev` branch with `nextflow run nf-core/methylseq -r dev`?
I believe that the issue has been fixed in https://github.com/nf-core/methylseq/pull/133/commits/043a51a9392a9648030f1276f043f4fa7b44802b

It was supposed to be fixed in 1.4.1, which has not been released yet:
https://github.com/nf-core/methylseq/pull/133

**Comment by sofiahaglund** [comment]
I see! 
Great, then we'll just wait and see I guess, thank you for your input! 👍

**Comment by ewels** [comment]
Thanks @phue - @sofiahaglund is trying to run the pipeline in our production environment which is offline, so trying the `dev` branch is kind of tricky. I'm sure you're right though, that the current dev version should work. Just need to do a release..!

**Comment by sofiahaglund** [comment]
I will close this now as this should be fixed with the new release being out, thanks @phue!
