### ISSUE TITLE
No internet mode

### ISSUE THREAD

**Issue by bazyliszek** [nf-core/methylseq#160]
Hey there! 

I just wanted to give a feedback on the pipeline running on a cluster without the internet.  I used the latest 1.5 version of the pipeline and I was able to run it quite nicely. I used Nextlfow version 20.04.01-all. I also used singularity image that I transfered to the HPC.

I still have these errors with preseq :  `'terminated with an error status (1) -- Error is ignored`. I thought it was fixed?

Also Graphviz is not working. Why it is so? I would expect it to be already in a singularity image. Anyway, this is great progress.  Cheers, Marcin

**Comment by ewels** [comment]
Hi @bazyliszek, thanks for the feedback - that's great to hear!

I still see the preseq error a lot and have been mostly ignoring it to be honest. I'm not sure what the cause is, if you or anyone fancies trying to dig down to find out what's wrong then that would be much appreciated.

Graphviz is launched by Nextflow itself, which runs outside of the singularity containers (which each of the pipeline steps are run inside). So we can't bundle Graphviz with the pipeline sadly - this is one dependency that you need to install yourself if you want the DAG output. See the [nextflow docs](https://www.nextflow.io/docs/latest/tracing.html#dag-visualisation) and the [Graphviz website](http://www.graphviz.org/).

Phil

**Comment by ewels** [comment]
I made a new issue specifically about preseq so that it doesn't get forgotten: https://github.com/nf-core/methylseq/issues/161
