### ISSUE TITLE
Define conda channel names in environment file

### ISSUE THREAD

**Issue by ewels** [nf-core/methylseq#74]
Docker builds are failing because the conda solving environment takes too long. Could be worth specifying the channel for each package to try to speed this up.

eg. `bioconda::multiqc=1.7` instead of just `multiqc=1.7`

**Comment by phue** [comment]
It's not just the docker builds, also running the pipeline with the conda profile fails because it takes to long to create the environment.

I just tested pinning the channels, it doesn't really help, building the environment still takes ages. I will do some further testing with a more recent conda build and the recommendations here:

https://github.com/bioconda/bioconda-recipes/issues/13774


By the way, do we still need the fastqc specific workaround after https://github.com/bioconda/bioconda-recipes/pull/12616 was merged?

**Comment by phue** [comment]
I think I found the culprit, it's the channel priorites. Pinning the channels however makes it slow again.. very confusing.

**Comment by ewels** [comment]
Thanks for looking in to this!
