### ISSUE TITLE
Reference genome downloaded for each sample

### ISSUE THREAD

**Issue by kokyriakidis** [nf-core/methylseq#90]
Let's say I start a new project with 40 samples, running methylseq with Singularity. At each iteration of `bismark_align` it downloads the genome files again and again and does not check if it has them already downloaded. This leads to an enormous amount of data storage needs and slow overall time. I run the pipeline with 1 sample only and with `--saveReference` option in order to download them and write its path on the config file.

I noticed this when I saw the network usage every time `bismark_align` starts. I goes max!

Also `--saveReferences` does not output the genome files in Results folder as supposed!

it happening or am I doing something wrong?

**Comment by phue** [comment]
I don't think this is related to Singularity.

See here:
https://github.com/nextflow-io/nextflow/issues/686

Please try if the issue persists if you run the pipeline with a nextflow version later than `19.02.0-edge`

**Comment by ewels** [comment]
Agreed - it is not to do with singularity, it's because it's pulling the references from s3. You can avoid this by downloading a local copy of the references and using that instead. If you download all of AWS-iGenomes then you can just use `params.igenomes_base` in your config file.

As @phue says - hopefully the latest release of nextflow will fix this, and the reference will only be downloaded once per pipeline run. I'd be interested to hear how you get on with this!

`--saveReferences` only does something when you ask the pipeline to generate the reference indexes. You're just referring to existing indexes here, so it doesn't really make sense to copy them again to the pipeline results. We can probably clarify this in the documentation.

Phil
